### ISSUE TITLE
Python 3.13 is not supported

### ISSUE THREAD

**Issue by veenstrajelmer** [mercator-ocean/copernicus-marine-toolbox#158]
When installing copernicusmarine with pip in a Python 3.13 environment, the installation fails:
```
(py313_env) c:\DATA>pip install copernicusmarine
ERROR: Ignored the following versions that require a different python version: 0.10.7 Requires-Python >=3.9,<3.12; 1.0.0 Requires-Python >=3.9,<3.12; 1.0.1 Requires-Python >=3.9,<3.13; 1.0.10 Requires-Python <3.13,>=3.9; 1.0.2 Requires-Python >=3.9,<3.13; 1.0.3 Requires-Python >=3.9,<3.13; 1.0.4 Requires-Python >=3.9,<3.13; 1.0.5 Requires-Python >=3.9,<3.13; 1.0.6 Requires-Python >=3.9,<3.13; 1.0.7 Requires-Python <3.13,>=3.9; 1.0.8 Requires-Python <3.13,>=3.9; 1.0.9 Requires-Python <3.13,>=3.9; 1.1.0 Requires-Python <3.13,>=3.9; 1.1.1 Requires-Python <3.13,>=3.9; 1.2.0 Requires-Python <3.13,>=3.9; 1.2.1 Requires-Python <3.13,>=3.9; 1.2.2 Requires-Python <3.13,>=3.9; 1.2.3 Requires-Python <3.13,>=3.9; 1.2.4 Requires-Python <3.13,>=3.9; 1.3.0 Requires-Python <3.13,>=3.9; 1.3.1 Requires-Python <3.13,>=3.9; 1.3.2 Requires-Python <3.13,>=3.9; 1.3.3 Requires-Python <3.13,>=3.9; 2.0.0a0 Requires-Python <3.13,>=3.9; 2.0.0a1 Requires-Python <3.13,>=3.9; 2.0.0a2 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement copernicusmarine (from versions: none)
ERROR: No matching distribution found for copernicusmarine
```

Python 3.13 was released on 7 Oct. Would be great if it can be supported asap, although I realize at least:
- [x] zarr requires numcodecs which does not yet support py3.13: https://github.com/zarr-developers/zarr-python/issues/2317 and https://github.com/zarr-developers/numcodecs/issues/593
- [x] netcdf4 has to be available on python 3.13 first: https://github.com/Unidata/netcdf4-python/issues/1370 >> netcdf4 1.7.2 contains no python 3.13 wheels for windows >> were added 1 day later
- [x] numpy<2 is required but does not support python 3.13: https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/159
- [x] remove the `<3.13` from `python = ">=3.9,<3.13"` pyproject.toml
- [x] add python 3.13 to ci

**Comment by renaudjester** [comment]
@veenstrajelmer Awesome! Thanks a lot for the work :D Let's keep tracking this!

**Comment by veenstrajelmer** [comment]
The issues with zarr are now fixed and netcdf4 will soon release python 3.13 wheels. After that, https://github.com/mercator-ocean/copernicus-marine-toolbox/issues/159 is the only blocker for python 3.13 support I think.

**Comment by veenstrajelmer** [comment]
@renaudjester was it ever consider to use h5netcdf instead of netcdf4? I am just curious since there are some lingering issues in netcdf4 that seem to stay unresolved and h5netcdf is developed close to xarray.

**Comment by renaudjester** [comment]
It hasn't been evaluated no! Do you have any ideas about pros and cons? 

As far as I read h5netcdf should be as fast as netcdf4. I don't know about the installation and dependencies if there are a lot of differences 🤔

**Comment by veenstrajelmer** [comment]
That is also what I heard, although I know of this bottleneck that can cause performance degradations in some cases: https://github.com/h5netcdf/h5netcdf/issues/195. I cannot judge the cons unfortunately.

I am not sure what copernicusmarine uses from netcdf4-python, but I learned last week that h5netcdf has a legacy api to make transfering as smooth as possible: https://h5netcdf.org/legacyapi.html. Although I guess it is also not a big effort to move to their normal API, depending on how entangled it is in the code. This is only worthwhile of course if it would of course benefit the toolbox, something I cannot judge.

**Comment by veenstrajelmer** [comment]
netcdf4 1.7.2 was released very recently and supports python 3.13 and numpy 2.0

**Comment by veenstrajelmer** [comment]
I think all issues are resolved, there are also netcdf4 1.7.2 python 3.13 wheels available for windows now (actually already 1 day after 1.7.2 was released). I see that python 3.13 support was already added in https://github.com/mercator-ocean/copernicus-marine-toolbox/pull/193. However, you could consider simplifying it again. Either way, I think this issue can be closed.

**Comment by renaudjester** [comment]
@veenstrajelmer Yes I agree thanks for tracking this! :D python 3.13 should be supported on main right now

**Comment by renaudjester** [comment]
@veenstrajelmer Yes I agree thanks for tracking this! :D python 3.13 should be supported on main right now
